defaults:
  - _self_
  - datamodule: s3dis.yaml
  - model: spt-2.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null
  - hparams_search: null
  - optional local: default.yaml
  - debug: null
task_name: train
optimized_metric: val/miou
tags:
  - dev
train: true
test: true
compile: false
ckpt_path: null
seed: null
float32_matmul_precision: highest